# Liquibase MongoDB Configuration
# This file contains the main Liquibase settings for MongoDB migrations

# Database Connection
# Note: URL will be overridden by Maven profiles for different environments
url: ${liquibase.url}
driver: liquibase.ext.mongodb.database.MongoLiquibaseDatabase

# Changelog Configuration
changeLogFile: database/mongodb/db/changelog/master.changelog.yaml

# Context and Labels Configuration
# These control which changesets run in which environments
contexts: ${liquibase.contexts}
labels: ${liquibase.labels}

# Liquibase Behavior Settings
logLevel: INFO
verbose: true
promptOnNonLocalDatabase: false

# Output Configuration
outputFile: target/liquibase-output.txt
outputFileEncoding: UTF-8

# MongoDB Specific Settings
# These settings optimize Liquibase for MongoDB usage
liquibase.mongodb.retryWrites: true
liquibase.mongodb.adjustTrackingTablesOnStartup: true
liquibase.mongodb.supportLiquibaseOnOtherDbs: true

# Backup and Safety Settings
liquibase.hub.mode: off
liquibase.command.updateSQL.outputFile: target/migration-${environment.name}.sql
liquibase.command.rollbackSQL.outputFile: target/rollback-${environment.name}.sql

# Performance Settings
liquibase.command.checks.run.cacheDuration: 300
liquibase.duplicateFileMode: WARN
liquibase.fileEncoding: UTF-8

# Security Settings  
liquibase.secureParsing: true
liquibase.strict: true

# Environment-specific overrides
# DEV Environment
---
spring:
  profiles: dev
liquibase:
  mongodb:
    connectionTimeout: 10000
    socketTimeout: 30000
    maxConnectionIdleTime: 60000

# STAGE Environment  
---
spring:
  profiles: stage
liquibase:
  mongodb:
    connectionTimeout: 15000
    socketTimeout: 45000
    maxConnectionIdleTime: 120000

# PRE-PROD Environment
---
spring:
  profiles: pre-prod
liquibase:
  mongodb:
    connectionTimeout: 15000
    socketTimeout: 45000
    maxConnectionIdleTime: 120000

# PROD Environment
---
spring:
  profiles: prod
liquibase:
  mongodb:
    connectionTimeout: 20000
    socketTimeout: 60000
    maxConnectionIdleTime: 300000
  # Production safety settings
  promptOnNonLocalDatabase: true
  logLevel: WARN
