# MongoDB Connection Configuration
# Environment-specific MongoDB connection settings

# Development Environment
development:
  connection:
    host: localhost
    port: 27017
    database: product_service_dev
    authSource: admin
    options:
      retryWrites: true
      w: majority
      readPreference: primary
      maxPoolSize: 10
      minPoolSize: 2
      maxIdleTimeMS: 60000
      waitQueueTimeoutMS: 10000
      serverSelectionTimeoutMS: 10000
      connectTimeoutMS: 10000
      socketTimeoutMS: 30000
  authentication:
    mechanism: SCRAM-SHA-256
    # Credentials should be provided via environment variables:
    # MONGODB_USERNAME, MONGODB_PASSWORD

# Staging Environment  
staging:
  connection:
    host: stage-mongodb-cluster
    port: 27017
    database: product_service_stage
    authSource: admin
    replicaSet: stage-replica-set
    options:
      retryWrites: true
      w: majority
      readPreference: primaryPreferred
      readConcern: majority
      maxPoolSize: 20
      minPoolSize: 5
      maxIdleTimeMS: 120000
      waitQueueTimeoutMS: 15000
      serverSelectionTimeoutMS: 15000
      connectTimeoutMS: 15000
      socketTimeoutMS: 45000
  authentication:
    mechanism: SCRAM-SHA-256
  ssl:
    enabled: true
    invalidHostNameAllowed: false

# Pre-Production Environment
pre-production:
  connection:
    host: preprod-mongodb-cluster
    port: 27017
    database: product_service_preprod
    authSource: admin
    replicaSet: preprod-replica-set
    options:
      retryWrites: true
      w: majority
      readPreference: primaryPreferred
      readConcern: majority
      maxPoolSize: 25
      minPoolSize: 5
      maxIdleTimeMS: 120000
      waitQueueTimeoutMS: 15000
      serverSelectionTimeoutMS: 15000
      connectTimeoutMS: 15000
      socketTimeoutMS: 45000
  authentication:
    mechanism: SCRAM-SHA-256
  ssl:
    enabled: true
    invalidHostNameAllowed: false

# Production Environment
production:
  connection:
    host: prod-mongodb-cluster
    port: 27017
    database: product_service_prod
    authSource: admin
    replicaSet: prod-replica-set
    options:
      retryWrites: true
      w: majority
      readPreference: primaryPreferred
      readConcern: majority
      writeConcern: majority
      maxPoolSize: 50
      minPoolSize: 10
      maxIdleTimeMS: 300000
      waitQueueTimeoutMS: 20000
      serverSelectionTimeoutMS: 20000
      connectTimeoutMS: 20000
      socketTimeoutMS: 60000
      heartbeatFrequencyMS: 30000
  authentication:
    mechanism: SCRAM-SHA-256
  ssl:
    enabled: true
    invalidHostNameAllowed: false
    caFile: /etc/ssl/mongodb-ca.pem
    pemKeyFile: /etc/ssl/mongodb-client.pem
  monitoring:
    enabled: true
    jmx: true

# Connection String Templates
# These are used by the Liquibase configuration
connectionStrings:
  development: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@localhost:27017/product_service_dev?authSource=admin&retryWrites=true"
  
  staging: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@stage-mongodb-cluster:27017/product_service_stage?authSource=admin&replicaSet=stage-replica-set&retryWrites=true&w=majority&ssl=true"
  
  pre-production: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@preprod-mongodb-cluster:27017/product_service_preprod?authSource=admin&replicaSet=preprod-replica-set&retryWrites=true&w=majority&ssl=true"
  
  production: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@prod-mongodb-cluster:27017/product_service_prod?authSource=admin&replicaSet=prod-replica-set&retryWrites=true&w=majority&readConcern=majority&ssl=true"

# Environment Variable Mappings
environmentVariables:
  development:
    - MONGODB_USERNAME=admin
    - MONGODB_PASSWORD=password123
    - MONGODB_DATABASE=product_service_dev
    
  staging:
    - MONGODB_USERNAME  # Set in Jenkins/K8s
    - MONGODB_PASSWORD  # Set in Jenkins/K8s secrets
    - MONGODB_DATABASE=product_service_stage
    
  pre-production:
    - MONGODB_USERNAME  # Set in Jenkins/K8s
    - MONGODB_PASSWORD  # Set in Jenkins/K8s secrets  
    - MONGODB_DATABASE=product_service_preprod
    
  production:
    - MONGODB_USERNAME  # Set in Jenkins/K8s
    - MONGODB_PASSWORD  # Set in Jenkins/K8s secrets
    - MONGODB_DATABASE=product_service_prod
